# Generated by Django 6.1.1 on 2026-09-09 12:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Roadmap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('goal', models.CharField(choices=[('weight_loss', 'Giảm cân'), ('muscle_gain', 'Tăng cơ'), ('endurance', 'Tăng sức bền'), ('flexibility', 'Tăng linh hoạt'), ('general', 'Tổng quát')], default='general', max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Đang thực hiện hay không')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roadmaps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lộ trình',
                'verbose_name_plural': 'Lộ trình',
                'db_table': 'roadmaps',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RoadmapPhase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=1, help_text='Thứ tự giai đoạn')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('roadmap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phases', to='roadmap.roadmap')),
            ],
            options={
                'verbose_name': 'Giai đoạn lộ trình',
                'verbose_name_plural': 'Giai đoạn lộ trình',
                'db_table': 'roadmap_phases',
                'ordering': ['order'],
            },
        ),
    ]
