# Generated by Django 6.1.1 on 2026-09-09 12:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schedule', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingJournal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Ngày tập thực tế')),
                ('title', models.CharField(help_text='Tên buổi tập', max_length=200)),
                ('notes', models.TextField(blank=True, help_text='Cảm nhận, ghi chú sau buổi tập', null=True)),
                ('duration_minutes', models.PositiveIntegerField(blank=True, help_text='Thời lượng tập (phút)', null=True)),
                ('mood', models.IntegerField(blank=True, choices=[(1, 'Rất tệ'), (2, 'Tệ'), (3, 'Bình thường'), (4, 'Tốt'), (5, 'Tuyệt vời')], help_text='Cảm giác sau buổi tập (1-5)', null=True)),
                ('calories_burned', models.PositiveIntegerField(blank=True, help_text='Calo đốt cháy (ước tính)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('schedule', models.OneToOneField(blank=True, help_text='Lịch tập tương ứng (nếu có)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal', to='schedule.trainingschedule')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Nhật ký tập',
                'verbose_name_plural': 'Nhật ký tập',
                'db_table': 'training_journals',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JournalExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Tên bài tập', max_length=200)),
                ('sets', models.PositiveIntegerField(blank=True, help_text='Số set', null=True)),
                ('reps', models.PositiveIntegerField(blank=True, help_text='Số rep mỗi set', null=True)),
                ('weight_kg', models.FloatField(blank=True, help_text='Tạ (kg)', null=True)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, help_text='Thời gian (giây) – dùng cho cardio/plank', null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='journal.trainingjournal')),
            ],
            options={
                'verbose_name': 'Bài tập trong nhật ký',
                'verbose_name_plural': 'Bài tập trong nhật ký',
                'db_table': 'journal_exercises',
            },
        ),
    ]
