# Generated by Django 6.1.1 on 2026-09-09 12:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Tên buổi tập', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Mô tả chi tiết buổi tập', null=True)),
                ('date', models.DateField(help_text='Ngày tập')),
                ('start_time', models.TimeField(blank=True, help_text='Giờ bắt đầu', null=True)),
                ('end_time', models.TimeField(blank=True, help_text='Giờ kết thúc', null=True)),
                ('difficulty', models.CharField(choices=[('easy', 'Nhẹ'), ('medium', 'Vừa'), ('hard', 'Nặng')], default='medium', max_length=10)),
                ('is_completed', models.BooleanField(default=False, help_text='Đã hoàn thành chưa')),
                ('notes', models.TextField(blank=True, help_text='Ghi chú thêm', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lịch tập',
                'verbose_name_plural': 'Lịch tập',
                'db_table': 'training_schedules',
                'ordering': ['date', 'start_time'],
            },
        ),
    ]
